version: "3.9"

services:
  chat-server:
    image: node:22-alpine
    container_name: chat-server
    working_dir: /usr/src/app
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    volumes:
      - ./:/usr/src/app
      # Anonymous volume to keep container's node_modules separate from host
      - /usr/src/app/node_modules
    command: sh -c "npm install && npm run dev"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:${PORT:-8080}/"]
      interval: 10s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  turn-server:
    image: coturn/coturn:latest
    container_name: turn-server
    ports:
      - "3478:3478"
      - "3478:3478/udp"
      - "5349:5349"
      - "5349:5349/udp"
      - "49152-65535:49152-65535/udp"
    volumes:
      - ./turn-server/turnserver.conf:/etc/coturn/turnserver.conf
    command: ["-c", "/etc/coturn/turnserver.conf"]
    restart: unless-stopped
    network_mode: host
